language: php
php:
    - 5.3.3

script:
    - php code-checker/src/code-checker.php

before_script:
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
